name: medical_examination_app
description: "A medical diary app for doctors to keep track of patient's health and medical records."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  alphabet_list_scroll_view: ^2.0.0
  alphabet_list_view: ^1.1.0
  dartz: ^0.10.1
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_secure_storage: ^9.2.2
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  internet_connection_checker: ^1.0.0+1
  provider: ^6.1.2
  rename: ^3.0.2
  shared_preferences: ^2.2.3
  speech_to_text: ^6.6.0
  tiengviet: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/.env
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21